// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoITeh10d0TgKAZ3Chp9_7CzLQAk2h1vg',
    appId: '1:304275998023:web:15e1d46b80d756e470f862',
    messagingSenderId: '304275998023',
    projectId: 'witwire-ebf8e',
    authDomain: 'witwire-ebf8e.firebaseapp.com',
    databaseURL: 'https://witwire-ebf8e.firebasedatabase.app', // IMPORTANT!
    storageBucket: 'witwire-ebf8e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwqLf5kiGU1zSb9NX4IS5HOHXlbv8YMnc',
    appId: '1:304275998023:android:15be9dd962d007d470f862',
    messagingSenderId: '304275998023',
    projectId: 'witwire-ebf8e',
    storageBucket: 'witwire-ebf8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiccvcgHntl7i1U-nIpoNf8uP3sT0vcCg',
    appId: '1:304275998023:ios:c60de58d65b2a73d70f862',
    messagingSenderId: '304275998023',
    projectId: 'witwire-ebf8e',
    storageBucket: 'witwire-ebf8e.appspot.com',
    iosBundleId: 'com.example.witwire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiccvcgHntl7i1U-nIpoNf8uP3sT0vcCg',
    appId: '1:304275998023:ios:c60de58d65b2a73d70f862',
    messagingSenderId: '304275998023',
    projectId: 'witwire-ebf8e',
    storageBucket: 'witwire-ebf8e.appspot.com',
    iosBundleId: 'com.example.witwire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoITeh10d0TgKAZ3Chp9_7CzLQAk2h1vg',
    appId: '1:304275998023:web:c17d67761503ec9b70f862',
    messagingSenderId: '304275998023',
    projectId: 'witwire-ebf8e',
    authDomain: 'witwire-ebf8e.firebaseapp.com',
    storageBucket: 'witwire-ebf8e.appspot.com',
  );
}
